### PR TITLE
Variant maps

### PR DESCRIPTION
**Pull request by hxrts**
Still needs a bit of maintenance before this pull request should be accepted. Adds global variant/CCF heat maps + subset heat maps. As well as pairwise subset & mutation prevalence + Fisher's exact plots. Also includes the standard phylogeny plots pulled straight from Charlotte's code which should be further adjusted before merging.

### CODE REVIEW

**Comment by hxrts** [comment]
this should now be working, however the master branch has progressed a good bit in the interim.

**Comment by raylim** [comment]
yeah, you could try rebasing in the current master. I'm almost ready to merge #171, however, so maybe you should hold off.

**Comment by inodb** [comment]
Let's do this one to rc. Also I don't think #171 is related to this PR, but I could be wrong

**Comment by inodb** [comment]
This first commit on this PR with "Ray's changes" can prolly be discarded. There's a bunch of ropeproject config files in there and what not

**Comment by hxrts** [comment]
there are only a couple files that need to be preserved:

```
/summary/variantMaps.mk
/summary/variantMaps.R
/summary/variantFishers.R
```

and then there is a facets fill fix included here as well

```
/facets/facetsFillGeneCN.R

```

and then the modifications to the main makefile

**Pull request closed without merging**
